### ISSUE TITLE
Update gaze dependency version

### ISSUE THREAD

**Issue by ivan-kleshnin** [wearefractal/glob-watcher#12] opened 2015-01-15 08:39 UTC
**glob-watcher** currently depends on **gaze@5.1**

Reference to caused issue in 6to5:
https://github.com/6to5/6to5/issues/489

There is already **gaze@6.4** which depends on newer **globule** which depends on newer **lodash**.
With newer **lodash** this issue no longer happens.

So updating to newer **gaze** would be very appreciating.

**Comment by heikki** [comment] 2015-01-15 08:58
Duplicate of https://github.com/wearefractal/glob-watcher/issues/10

**Closed** 2015-01-15 20:25 UTC

**Comment by fa7ad** [comment] 2016-06-11 09:43
bump! gaze is at 1.0.0 any updates on this?

**Comment by phated** [comment] 2016-06-11 15:01
They reverted to the version we use and released it as 1. There's absolutely no reason to upgrade.

**Comment by fa7ad** [comment] 2016-06-12 00:28
that would just be a simple package.json version bump, right?
